name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
#        arch: [x86_64, aarch64]
        arch: [x86_64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.arch }}" == "x86_64" ]]; then
            echo "TARGET=x86_64-unknown-linux-gnu" >> $GITHUB_ENV
            echo "DIST=bysqr-linux-x86_64" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.arch }}" == "aarch64" ]]; then
            echo "TARGET=aarch64-unknown-linux-gnu" >> $GITHUB_ENV
            echo "DIST=bysqr-linux-aarch64" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "x86_64" ]]; then
            echo "TARGET=x86_64-apple-darwin" >> $GITHUB_ENV
            echo "DIST=bysqr-darwin-x86_64" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "aarch64" ]]; then
            echo "TARGET=aarch64-apple-darwin" >> $GITHUB_ENV
            echo "DIST=bysqr-darwin-aarch64" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          cargo build --release --bin bysqr --target $TARGET

      - name: Archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p target/dist
          cp target/$TARGET/release/bysqr target/dist/$DIST

      - name: Upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
